### ISSUE TITLE
OPMrun .exe file

### ISSUE THREAD

**Issue by User22814** [OPM/opm-utilities#66]
Hello to all! How can I get the .exe file to run just like an application. I can already run through the terminal. With command:
`python opmrun.py`
Then I tried to build with **pyinstaller** like in instruction:
`pyinstaller --onefile opmrun.py` 
The build is successful. build and dist folders are created. In dist folder there is an .exe file, but when launched, it does not bring up the opmrun window, as when launched from the terminal.
![Error_OPMrun](https://user-images.githubusercontent.com/99706236/154412180-80b0880b-7648-433c-88ba-159dd57e7da2.jpg)

**Comment by User22814** [comment]
But when I start with cmd terminal. All is working.

![OPMrun_terminal](https://user-images.githubusercontent.com/99706236/154412872-83fbac11-87d0-4112-bce8-d41bca16ad88.jpg)

**Comment by OPMUSER** [comment]
Building the executable used to work previously but has not worked with the last couple of releases, I have tried to fix this several times but to no available.

**Comment by User22814** [comment]
> Building the executable used to work previously but has not worked with the last couple of releases, I have tried to fix this several times but to no available.

Can you tell me which release I can run in this form?

**Comment by OPMUSER** [comment]
To be honest I don't know but it was before I added the functions to be able to run under Windows and to use WSL.
