### ISSUE TITLE
Problem launching OPMRUN

### ISSUE THREAD

**Issue by gnrteixeira** [OPM/opm-utilities#78]
Hello all.
I am not managing to launch OPMRUN. in Ubuntu 22.04 It returns an error in the "run_command" function.
I am running python3.10 which is the default installation.
Has anyone had a similar issue?

![Captura de tela de 2023-05-19 14-04-44](https://github.com/OPM/opm-utilities/assets/134089211/167094b4-1fea-41b2-a65c-c62f26e053a4)

Guilherme

**Comment by akva2** [comment]
opmrun is now a proper python package. Install using e.g. 'pip3 install .', then execute using the 'opmrun' command.

**Comment by gnrteixeira** [comment]
Thanks for your reply.
What would be the name of the package? I tried "pip3 install opmrun" and it did not work.

**Comment by akva2** [comment]
It is not in pypi.  From top of the git, execute what i wrote - 'pip3 install .' - install current directory.

**Comment by gnrteixeira** [comment]
It worked. Thanks for your help, Arne.
